export const CATCHABLE_DELETE = 'CATCHABLE_DELETE';
export const CATCHABLE_DELETE_ALL = 'CATCHABLE_DELETE_ALL';
export const CATCHABLE_FILTER_UPDATE = 'CATCHABLE_FILTER_UPDATE';
export const CATCHABLE_LIST = 'CATCHABLE_LIST';
export const CATCHABLE_SET_LIST_IN_PROGRESS = 'CATCHABLE_SET_LIST_IN_PROGRESS';
export const CATCHABLE_SET_GET_IN_PROGRESS = 'CATCHABLE_SET_GET_IN_PROGRESS';
export const CATCHABLE_SET_CURRENT = 'CATCHABLE_SET_CURRENT';
